version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:latest
    volumes:
      - .:/src
    working_dir: /src/SmartMinioManager
    command: /bin/bash -c "dotnet restore && dotnet publish -c Release -o ./obj/Docker/publish"
